### ISSUE TITLE
The fireball sprites are broken when hitting buildings(regression)

### ISSUE THREAD

**Issue by turican0** [GrimSqueaker/remc2#10] opened 2021-01-28 18:21 UTC

**Comment by GrimSqueaker** [comment] 2021-01-28 20:55
For documentation: The regression has been introduced with the following commits.
```
$ git log 2b098da3^..aac4f686
commit aac4f68699453da60c014428242bf01be87fd7e3
Author: turican0 <41465132+turican0@users.noreply.github.com>
Date:   Tue Jan 26 20:04:27 2021 +0100

    rewrite nest arrays to sctruct

commit 3533ac298561a0fd078c2bbb9e1473666fc0d4db
Author: Tomas Vesely <turican0@gmail.com>
Date:   Tue Jan 26 15:27:53 2021 +0100

    next fixes

commit 3de3e51912699518b86acaeec5034e82d6f02669
Author: turican0 <41465132+turican0@users.noreply.github.com>
Date:   Mon Jan 25 18:42:54 2021 +0100

    modify info text

commit 2b098da3fb4b9294456955bcd629368826458451
Author: turican0 <41465132+turican0@users.noreply.github.com>
Date:   Mon Jan 25 18:37:32 2021 +0100

    add informations for next testing
```

**Comment by GrimSqueaker** [comment] 2021-01-28 22:31
This seems to be fixed with https://github.com/GrimSqueaker/remc2/pull/9
@thobbsinteractive, could you confirm this, please?

**Comment by thobbsinteractive** [comment] 2021-01-28 23:10
Yes it seems much better, however the Archers are much harder to kill from
some reason.

I tried to count the number of shots to kill an Archer. The DOS Box and my
Repos Dev build it is 5 shots.
With your Dev branch it is 6-7 or (with the archers much further away 15-20
shots.

It seems like the sprites are missing their target a lot of the time,
despite being shot accurately. Perhaps there are still collision issues?

I realize you were probably hoping for better news

Kind regards

Tim

**Comment by GrimSqueaker** [comment] 2021-01-28 23:35
Hi Tim,
thanks for the feedback. Does this also affect the stable branch for which I have a PR opened for?
That would help me track the problem down.
Cheers,
Sebastian

**Comment by thobbsinteractive** [comment] 2021-01-29 06:09
I pulled your repos Development branch, that's where you had merged too
right?

My guess is that this is a indexing issue in the game update code with the
next matrix sizes. Maybe it's skipping a movement location in it flight and
That's why it's less accurate over distance or not colliding.

In other news, I was reading that it is common in C and c++ to have a def.h
file that contains all the common data types in it and to define custom
types for even the most common stuff. Now there is a def.h but we also take
types from DOSbox.h (8bitu) and other places. I think the idea in the old
days was with one location it made it easier to port to different OS's
because you could just change the def.h file.

Structures should really have their own files so I would leave those for
now, but
If I refactor the code to have the definitions all in one place we'd all
need to sync up with that change asap. Anyway what do you think of it as an
idea?

**Comment by GrimSqueaker** [comment] 2021-01-29 22:20
Hi Tim,

I can confirm the problem with fireballs not hitting targets correctly on my development branch. It also seems to affect the posses mana spell which also needs to be fired multiple times before hitting.
But on the stable branch of my repository this regression is not present. I have one open PR from my stable branch to your development branch which should be safe for you to merge.
I would propose that we do not sync our dev branches until this regression is fixed. But in order to keep the branches from diverging too much I keep on managing the stable branch with those commits cherry-picked that do not show this regression. We can use this to sync in your direction. On the other hand I regularly pull your development branch into my stable and development branches.
This way I can keep up with @turican0's changes as well as yours. And by the time the regression is fixed we can get all development branches in sync again.

Yes, it makes sense to define common types in one location and also to define types according to semantics. A char[4] could be storage for a double word or for a 4 letter string. Introducing a type for each makes the meaning clear and makes the compiler check if they are mixed somewhere by accident and consequently failing to compile.

Regarding the dosbox types: I am a strong proponent of sticking as close as possible to the ISO C++ standard (https://en.cppreference.com is a great resource). The reason is that this is the best way to make the code portable. In my company we maintain a codebase of about 10M lines of C++ code that compiles on Windows and Linux and we do so by allowing only ISO C++17 which prevents GCC and MSVC specific features. Therefore, I would like to replace all Bit8u and __int8u by the standard (since C++11) type uint8_t and so on.

This C++ style vs C goes even further. I would like to replace the plain C arrays by std::array which can either be used like a C array with no performance impact or by using the .at member function which introduces boundary checks at runtime for little overhead. This can fix occasional crashes that I have seen which in all cases have been caused by out of bound memory access so far. Also most of the dynamically allocated arrays should be replaced by std::string and std::vector. The little overhead is negligible and the gain is huge by not having to deal with memory handling. Modern C++ code should neither use malloc nor new/delete and I'm not even starting with that pesky sprintf and strcpy :-D .
But this would touch a lot of code at once which I will not do until @turican0 has finished rewriting the arrays as structs. Otherwise merging the changes can become a nightmare.

You are right that structures should get their own files. And so should also all logical units. By that I mean something like sprite related functions and types, rendering related functions etc. 
If you go ahead with this refactoring just tell me and I will merge / cherry-pick this to all my branches so that you can concentrate on the important things and not have to worry about repo handling. :-)

What do you think of this, @turican0 ?

Cheers,
Sebastian

**Comment by thobbsinteractive** [comment] 2021-01-29 22:46
Hi Sebastian

I will test that PR out tomorrow. I am happy to use the
https://en.cppreference.com reference. I was going to propose we use a
standard, but honesty this is the first C and C++ code I have written since
college so I was a little clueless as to what standard to use. I am spoilt
in my line of work as I use .Net or Java so memory management is rare as is
knowing if something is in scope or not. So I am a little out of practice
:) but getting the hang of it again.

I knew about the STL when I was using sprintf to sort the paths but I also
decided to re-use the tried and test code that was there already since I
was worried about the portability of using the STL library. So no New and
Delete? I thought that was the point of C++, no more malloc? How do you
instantiate classes? As only stack or static variables? Clearly I have more
to learn here.

If you want to start our typedefs please go ahead and replace Bit8u, I hate
debugging with a char, its more of a pain to convert to int or hex. I'll
happily cherry pick that change. You can also make it on another branch if
you want to keep it separate from your current work. I will get to it
eventually, but draw distance and resolution comes first. Hopefully that
work will also help identify more of the structs. Some are no doubt
matrices for 3D transformations, but telling what they are when they are
filled with hex is difficult.

Keep up the good work

Tim

**Comment by turican0** [comment] 2021-01-30 11:23
Yes, at now is better only partially synchronise(you synchronize code from my development brach). So I won't post any pulls yet. When I finish and fix some bugs you can back to full synchronization scheme.
Yes code have many parts with mishmash types. We must maximal clear retyping (Bit8u* to int, Bit8u* to Bit32u*, char[4] to dword). And union structures, too. Some this I rewrite when changes from arrays to struct,next retyping we must do in next times.
I agree with rewrite types to C++11 standard, please do it(after full synchronization code). Changes array to vectors and char* to strings is ok, but this make it difficult compare code with dosbox memory. This changes I would postpone until after most of the bugs.
Yes, I write after end basic rewriting and bug fixing, and we can synchronize branches.
Thank you, Tom.

**Comment by GrimSqueaker** [comment] 2021-01-30 22:12
Hi Tim,
Hi Tom,
:-)

C++ changed a lot with the introduction of C++11. One of the problems with malloc/new/delete and raw pointers in general is that ownership is unclear which can lead to not cleaning up correctly or worse using freed memory. In modern C++ new/delete is discouraged and the best practise is using std::shared_ptr (with reference counting) or std::unique_ptr (only one owner) which make it clear who ownes the memory. You will find that this comes closer to managed languages like C#/Java without requiring garbage collection.

I think I will concentrate on some more tooling and my "FIXME" comments next. For example, I have prepared clang-tidy in CMake which can be used to automatically clean up the code. For example it can remove unused function parameters. I think everything that makes the code shorter and cleaner will help to work on it. But as Tom described some of this will have to wait until binary comparisons with dosbox are not necessary any longer.

Thank you guys for the fun side project,
Sebastian

**Closed as completed** 2021-02-02 23:00 UTC
Labels: bug

**Comment by GrimSqueaker** [comment] 2021-02-02 23:01
Hi all,
I think I have fixed this with commit 5862ac94.
Could you please check, @thobbsinteractive ?
It would be good if we can sync your dev branch again.
Cheers,
Sebastian

**Comment by thobbsinteractive** [comment] 2021-02-03 09:43
Yeah I will try and take a look tonight, although my first priority is
getting the sonar scan working.
Eitherway I will have it tested in the next couple of days.

**Comment by thobbsinteractive** [comment] 2021-02-04 19:08
Hi Sebastian

I pull your dev branch (with the commit you mentioned) I am afraid the game
crashed at the start of the new level:

[image: image.png]
Unhandled exception at 0x7AC9F2F6 (ucrtbased.dll) in remc2.exe: An invalid
parameter was passed to a function that considers invalid parameters fatal.

in Bit32u compare_with_sequence(...) line 1219 of engine_support.cpp. It
looks like this is MS Build specific code.

Let me know when you want me to test it again.

Kind regards

Tim

**Comment by thobbsinteractive** [comment] 2021-02-04 19:24
I think I see the problem.

The hard-coded paths. I think a debug method is being called and it is
using one of the "prenos" paths.

Tom said he was comparing memory structures, it is possible there is on
commented in.

Kind regards

Tim

**Comment by thobbsinteractive** [comment] 2021-02-04 20:23
Hi Seb,

Some good news, the Sonar scan is working and merged.
This should make you laugh:
https://sonarcloud.io/dashboard?id=thobbsinteractive_magic-carpet-2-community-patch

**Comment by GrimSqueaker** [comment] 2021-02-04 20:55
Hi Tim,

currently I have to set RELEASE_GAME in sub_main.cpp, to circumvent the memory comparisons. But I guess, I will set it by default today. As I will also change the default resolution to Full-HD. I have two displays. One 1440p and on 4k. the 640x480 is like playing on a postage stamp.
I will fix these two issues, merge Tom's latest changes, and try to get the regression with loading saved games (rendering the selected save game name in the wrong location) fixed. The we should really try to sync the dev branches again. 

Great achievement with SonarCloud. So it would make sense to fix the bug issues asap. Some of the array out of bounds accesses and returning non-initialised variables may explain some crashes that I see occasionally. This is in line with what the clang tools complain about and when I run the game with sanitizers enabled.
For the thousands of code smells. Well, I guess we were aware of that already.
And yes, the major HTML problems... I guess we can safely add *.html to the exclude list.

I wonder if SonarCloud will work if I merge this into my fork. I still have my credentials set up.

Cheers,
Sebastian

**Comment by thobbsinteractive** [comment] 2021-02-04 21:14
You might have to change some sonar.properties file, but it should work.
The sonar cloud website has a step by step guide that even generates the
config. But Either way any pull request to my dev branch will be evaluated.

I will take a look at the sonar results over the weekend and start fixing
stuff. I'd love to remove the 8bitu char type. Most complaints are from
sonar thinking any array of these should be std::string

**Comment by GrimSqueaker** [comment] 2021-02-04 22:43
> [..] Most complaints are from sonar thinking any array of these should be std::string

And it is right about that :-)

**Comment by turican0** [comment] 2021-02-05 16:00
Hi Tim, good work, sonar is perfect tool for finding problematic parts of code. We can fix parts by removing compiler warnings, too.
Changing char to int8_t is ok. But please std::string use only for print text, not in structs at now. Debugging with binary compactibility is easyer.
Later we'll have to create procedures for translate binary save files from/to structures - in 32bit is memcopy ok now, but in 64bit will be problem with pointers. This and similar translate procedures will be good tool to create data structure for debugging, and we will be able to advaced changed in data structures.

Hi,
Tom.

**Comment by thobbsinteractive** [comment] 2021-02-05 20:02
Hi Tom.

Hopefully I have fixed the "analysis" permissions now in Sonarcloud, so
next pull request to my repo should be able to send the analysis results
(sonar has some stupid default settings).

I want to start a defs.h file for all the existing DosBox types, starting
with a definition for Bit8u. I am happy to change it from an unsigned char
use to int8_t (as its c++ 11 a multiplatform) as this will remove a lot of
sonar complaints and my own annoyances debugging.
The reason for still using a defs.h file and keeping Bit8u rather than
simply replacing Bit8u everywhere in the code is to make the code more
portable. Since a central defs.h file will allow any future platform coders
to define compatible types.

But this will be a big change to sync. Are you guys happy for me to do this
since it will effect your branches or do you want me to wait a bit?

Kind regards

Tim

**Comment by GrimSqueaker** [comment] 2021-02-05 22:17
Hi,

I think, the file `dosbox_files/config.h` is problematic and should be removed. For example `#define SIZEOF_UNSIGNED_INT		4` is wrong on 64 bit. I guess this was generated for a 32 bit compilation of DOSBOX and then copied here. I would prefer to just replace Bit8u by int8u_t everywhere (and so on). Because this is in the language standard it is the most portable way to do it and it makes the code easier to read for newcomers instead of introducing custom types.

I think the only important thing is, that for the moment everything stays binary compatible with running the game in DOSBOX. This includes C-strings and arrays but we are free to rename `Bit8s` to `int8_t` and so on. We could even go further and replace things like `Bit8u unk_D3F91x[0x5]` by `std::array<int8u_t,0x5> unk_D3F91x` which both have exactly the same memory representation but the latter has the benefit of compile time out of bounds checks and you can even do `unk_D3F91x.at(x)` instead of `unk_D3F91x[x]` for additional run time bounds checks.
Sorry for pushing so hard with that stuff, but when I run the game with sanitizers enabled it crashes in a lot of places because of out-of-bounds accesses which are a major pain when considering a 64 bit build.

On the other hand the file `engine/defs.h` is useful for low level stuff and could be extended if needed.

Cheers,
Sebastian

**Comment by turican0** [comment] 2021-02-06 10:18
Hi,

yes we can remove config.h.(There was so much work on the code that I never got to clean it.)
I would use int8_t types directly, if they were not defined on some platform, they can be defined.
Rewriting from Bit8s to int8_t is easier(just rename the types). Rewriting to std::array would probably require manual rewriting, or some script.
Anyway, before you start, please let me know if I suspend a major rewrite of the code.
I will leave the removal / preservation of defs.h to you. I'm not a programmer. (it's just my hobby)

Tom.

**Comment by thobbsinteractive** [comment] 2021-02-06 11:27
Cool. I will start with today with replacing the those types. Testing as I
go. There will be a separate check-in for each type. That should reduce the
codec smells. I will make a pull request to dev and you guys can review it
then sync your branches once it's merged

**Comment by turican0** [comment] 2021-02-06 15:32
Please merge my pull reguest "update 210206" before this action,
Tom.

**Comment by thobbsinteractive** [comment] 2021-02-06 16:14
Unfortunately its too late I have already do a lot of the changes Tom.
I will take a look at your update as see if I can merge it in this current
branch, if not it is no problem we will just have to merge later.

**Comment by turican0** [comment] 2021-02-06 17:07
Well, maybe the later merger will be more laborious, but there's nothing you can do now :)
Tom.

**Comment by GrimSqueaker** [comment] 2021-02-06 17:23
I can try to merge both your dev branches and resolve conflicts.
Regarding the std::array : You are right. This is a manual process. We might just change them along the way when we touch some code anyway. Because you cannot just pass the array name when the function takes a pointer of the element type. So there might be some changes involved to make the compiler happy.
